<<<<<<< HEAD
# Nome do job
name: Primeiro Workflow, Hello World

on:
  workflow_dispatch:
jobs:
  job_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir mensagem de Hello World
        run: echo "Hello, World!"
=======
# Nome do workflow
name: Hello World
on:
  workflow_dispatch:
jobs:
  # Nome do job
  hello-world:
    # Definição do SO que vai executar o job
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
>>>>>>> 0e45051 (adicionando dependencia entre jobs)
